### ISSUE TITLE
compiled release version

### ISSUE THREAD

**Issue by voshond** [ryanmcgrath/1.1.1.1-macOS#2]
Hi!

Would like to give the app a shot but i was not able to build the app with a free dev account in xcode and i was wondering if you would be able to package one together?

I would hate to setup the DNS for each and every network i use.

**Comment by Morteza-Rastgoo** [comment]
Same here

**Comment by ryanmcgrath** [comment]
CloudFlare has a beta for their 1.1.1.1 on macOS, it seems - give it a whirl! https://1.1.1.1/beta/
